steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/music-reviews', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/music-reviews']
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - 'run'
  - 'deploy'
  - 'music-reviews'
  - '--image'
  - 'gcr.io/$PROJECT_ID/music-reviews'
  - '--region'
  - 'europe-west1'  # Changed from us-central1 to europe-west1 (Belgium)
  - '--platform'
  - 'managed'
  - '--allow-unauthenticated'